### ISSUE TITLE
Fabric not supporting VectorDrawables

### ISSUE THREAD

**Issue by Gennadiyev** [berict/Tapad#146]

**Comment by BedrockDev** [comment]
```
Fatal Exception: android.content.res.Resources$NotFoundException: File res/drawable/ic_image_album_placeholder.xml from drawable resource ID #0x7f020094
       at android.content.res.Resources.loadDrawable(Resources.java:2154)
       at com.huawei.android.content.res.ResourcesEx.loadDrawable(ResourcesEx.java:716)
       at android.content.res.Resources.getDrawable(Resources.java:741)
       at com.squareup.picasso.RequestCreator.getPlaceholderDrawable(RequestCreator.java:676)
       at com.squareup.picasso.RequestCreator.into(RequestCreator.java:664)
       at com.squareup.picasso.RequestCreator.into(RequestCreator.java:601)
       at com.bedrock.padder.adapter.PresetStoreAdapter.onBindViewHolder(PresetStoreAdapter.java:164)
       at com.bedrock.padder.adapter.PresetStoreAdapter.onBindViewHolder(PresetStoreAdapter.java:37)
       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
       at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
       at android.view.View.measure(View.java:16566)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:716)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:609)
       at android.view.View.measure(View.java:16566)
       at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1420)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:482)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16566)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
       at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1391)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
       at android.view.View.measure(View.java:16566)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16566)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:716)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:609)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:716)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:609)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2327)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1988)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1163)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1345)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1050)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5935)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
       at android.view.Choreographer.doCallbacks(Choreographer.java:593)
       at android.view.Choreographer.doFrame(Choreographer.java:562)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5336)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
       at android.content.res.Resources.loadDrawable(Resources.java:2150)
       at com.huawei.android.content.res.ResourcesEx.loadDrawable(ResourcesEx.java:716)
       at android.content.res.Resources.getDrawable(Resources.java:741)
       at com.squareup.picasso.RequestCreator.getPlaceholderDrawable(RequestCreator.java:676)
       at com.squareup.picasso.RequestCreator.into(RequestCreator.java:664)
       at com.squareup.picasso.RequestCreator.into(RequestCreator.java:601)
       at com.bedrock.padder.adapter.PresetStoreAdapter.onBindViewHolder(PresetStoreAdapter.java:164)
       at com.bedrock.padder.adapter.PresetStoreAdapter.onBindViewHolder(PresetStoreAdapter.java:37)
       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
       at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
       at android.view.View.measure(View.java:16566)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:716)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:609)
       at android.view.View.measure(View.java:16566)
       at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1420)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:482)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16566)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
       at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1391)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
       at android.view.View.measure(View.java:16566)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16566)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:716)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:609)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1430)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:716)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:609)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5145)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2327)
       at android.view.View.measure(View.java:16566)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1988)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1163)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1345)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1050)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5935)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
       at android.view.Choreographer.doCallbacks(Choreographer.java:593)
       at android.view.Choreographer.doFrame(Choreographer.java:562)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5336)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by BedrockDev** [comment]
needs to be changed to `png`
