### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException at at com.bedrock.padder.helper.FileHelper$Decompress.onPostExecute

### ISSUE THREAD

**Issue by BedrockDev** [berict/Tapad#152]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setIndeterminate(boolean)' on a null object reference
       at com.bedrock.padder.helper.FileHelper$Decompress.onPostExecute(FileHelper.java:206)
       at com.bedrock.padder.helper.FileHelper$Decompress.onPostExecute(FileHelper.java:104)
       at android.os.AsyncTask.finish(AsyncTask.java:660)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by BedrockDev** [comment]
what i duplicated
