### ISSUE TITLE
Preset store retrying forever

### ISSUE THREAD

**Issue by BedrockDev** [berict/Tapad#163]
Need to quit retrying on the connection lost

```
07-18 12:32:19.016 11053-11053/com.bedrock.padder E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.bedrock.padder, PID: 11053
                                                                    com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
                                                                        at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1428)
                                                                        at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1417)
                                                                        at com.bedrock.padder.fragment.PresetStoreOnlineFragment$4.run(PresetStoreOnlineFragment.java:190)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-18 12:32:19.261 11053-12211/com.bedrock.padder W/ExponenentialBackoff: network unavailable, sleeping.
07-18 12:32:19.261 11053-12211/com.bedrock.padder E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.android.gms.internal.zzbtk: Please sign in before trying to get a token.
07-18 12:32:20.338 11053-12211/com.bedrock.padder W/ExponenentialBackoff: network unavailable, sleeping.
07-18 12:32:20.339 11053-12211/com.bedrock.padder E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.android.gms.internal.zzbtk: Please sign in before trying to get a token.
07-18 12:32:21.496 11053-12211/com.bedrock.padder W/ExponenentialBackoff: network unavailable, sleeping.
07-18 12:32:21.497 11053-12211/com.bedrock.padder E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.android.gms.internal.zzbtk: Please sign in before trying to get a token.
07-18 12:32:22.738 11053-12211/com.bedrock.padder W/ExponenentialBackoff: network unavailable, sleeping.
07-18 12:32:22.739 11053-12211/com.bedrock.padder E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.android.gms.internal.zzbtk: Please sign in before trying to get a token.
07-18 12:32:23.879 11053-12211/com.bedrock.padder W/ExponenentialBackoff: network unavailable, sleeping.
07-18 12:32:23.880 11053-12211/com.bedrock.padder E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.android.gms.internal.zzbtk: Please sign in before trying to get a token.
07-18 12:32:24.924 11053-12211/com.bedrock.padder W/ExponenentialBackoff: network unavailable, sleeping.
07-18 12:32:24.926 11053-12211/com.bedrock.padder E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.android.gms.internal.zzbtk: Please sign in before trying to get a token.
07-18 12:32:25.986 11053-12211/com.bedrock.padder W/ExponenentialBackoff: network unavailable, sleeping.
07-18 12:32:25.988 11053-12211/com.bedrock.padder E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.android.gms.internal.zzbtk: Please sign in before trying to get a token.
07-18 12:32:27.196 11053-12211/com.bedrock.padder W/ExponenentialBackoff: network unavailable, sleeping.
07-18 12:32:27.198 11053-12211/com.bedrock.padder E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.android.gms.internal.zzbtk: Please sign in before trying to get a token.
07-18 12:32:28.219 11053-12211/com.bedrock.padder W/ExponenentialBackoff: network unavailable, sleeping.
07-18 12:32:28.222 11053-12211/com.bedrock.padder E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.android.gms.internal.zzbtk: Please sign in before trying to get a token.
```

**Comment by BedrockDev** [comment]
detailed informations on replicating this?

**Comment by BedrockDev** [comment]
Reopen this on further issues, closing for now.
