### ISSUE TITLE
Colors option in settings crashes the app.

### ISSUE THREAD

**Issue by Gennadiyev** [berict/Tapad#192]
(Which is pretty strange, the same part works alright before)

**Comment by BedrockDev** [comment]
on fix

**Comment by BedrockDev** [comment]
```

10-21 21:27:55.480 19678-19678/com.bedrock.padder E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.bedrock.padder, PID: 19678
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Integer[] com.bedrock.padder.model.preferences.ItemColor.getColorButtonRecents()' on a null object reference
                                                                        at com.bedrock.padder.adapter.ColorAdapter.getItemCount(ColorAdapter.java:165)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3603)
                                                                        at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3103)
                                                                        at android.view.View.measure(View.java:21998)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
                                                                        at android.view.View.measure(View.java:21998)
                                                                        at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1446)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                        at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:512)
                                                                        at android.view.View.measure(View.java:21998)
                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                        at android.view.View.measure(View.java:21998)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                        at android.view.View.measure(View.java:21998)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
                                                                        at android.view.View.measure(View.java:21998)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                        at android.view.View.measure(View.java:21998)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
                                                                        at android.view.View.measure(View.java:21998)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:721)
                                                                        at android.view.View.measure(View.java:21998)
                                                                        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2410)
                                                                        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1498)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                        at android.os.Handler.handleCallback(Handler.java:789)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
